from setuptools import setup

APP = ["src/main.py"]

DATA_FILES = [
    ("assets", ["assets/4Charm.icns"]),
]

OPTIONS = {
    "argv_emulation": False,
    "iconfile": "assets/4Charm.icns",
    "arch": "arm64",
    "plist": {
        "CFBundleIconFile": "4Charm",
        "CFBundleName": "4Charm",
        "CFBundleDisplayName": "4Charm",
        "CFBundleIdentifier": "com.RazorBackRoar.4Charm",
        "CFBundleVersion": "5.1.0",
        "CFBundleShortVersionString": "5.1.0",
        "NSHumanReadableCopyright": "Copyright © 2025 RazorBackRoar. All rights reserved.",
        "NSHighResolutionCapable": True,
        "NSRequiresAquaSystemAppearance": False,
        "LSMinimumSystemVersion": "11.0",
        "LSApplicationCategoryType": "public.app-category.utilities",
        "CFBundleSupportedPlatforms": ["MacOSX"],
        "NSAppTransportSecurity": {"NSAllowsArbitraryLoads": True},
    },
    "packages": ["PySide6", "requests", "urllib3", "certifi", "bs4"],
    # Explicitly excluding PyQt6 is good practice
    "excludes": [
        "PyQt6",
        "PyQt5",
        "tkinter",
        "test",
        "unittest",
        "PyInstaller",
        "PySide6.QtQuick",
        "PySide6.QtQml",
        "PySide6.QtNetwork",
        "PySide6.QtMultimedia",
        "PySide6.QtSql",
        "PySide6.QtTest",
        "PySide6.QtDesigner",
        "PySide6.QtXml",
        "PySide6.QtSvg",
        "PySide6.QtWebEngine",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebEngineCore",
        "PySide6.QtBluetooth",
        "PySide6.QtDBus",
        "PySide6.QtNfc",
        "PySide6.QtPositioning",
        "PySide6.QtPrintSupport",
        "PySide6.QtRemoteObjects",
        "PySide6.QtScxml",
        "PySide6.QtSensors",
        "PySide6.QtSerialBus",
        "PySide6.QtSerialPort",
        "PySide6.QtStateMachine",
        "PySide6.QtTextToSpeech",
        "PySide6.QtWebChannel",
        "PySide6.QtWebSockets",
        "PySide6.Qt3DCore",
        "PySide6.Qt3DInput",
        "PySide6.Qt3DLogic",
        "PySide6.Qt3DRender",
        "PySide6.Qt3DExtras",
        "PySide6.Qt3DAnimation",
    ],
    "includes": ["PySide6.QtCore", "PySide6.QtWidgets", "PySide6.QtGui"],
    "optimize": 2,
    "compressed": True,
    "no_chdir": True,
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
)
